version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      DATABASE_HOST: localhost
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_NAME: postgres
      DATABASE_SCHEMA: public
      DATABASE_SYNCHRONIZE: false
      JWT_SECRET: 74YLbq4%c!wU
      JWT_EXPIRATION_TIME: 1800
      JWT_REFRESH_TOKEN_SECRET: 7jML9q4-c!s0
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 86400
    volumes:
      - .:/app/src
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine3.17
    restart: always
    environment:
      POSTGRES_USER: postgres
      DATABASE_PASSWORD: 123
      POSTGRES_DB: postgres
